//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourZillaZone12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLabourZilla
    {
        public string LoginId { get; set; }
        public string APassword { get; set; }
    }
}
