//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourZillaZone12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public string TName { get; set; }
        public string Temail { get; set; }
        public string TprojectName { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
    }
}
